name: Run tests
on:
  push:
    branches:
      - "**"
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
      - run: npm install
      - run: npm run typecheck
      - run: npm test
      - run: npm run format:check
